Usunięto pandę
mlodyhubson/malpki pull request #1
Opened 2023-11-23 14:42 UTC by majaomelaniuk

siema hubson usunęłam pandę ok?

2023-11-23 14:44 UTC, mlodyhubson commented
ok
ale dodaj jeszcze lemura

2023-11-23 14:45 UTC, mlodyhubson requested changes
ok
ale dodaj jeszcze lemura
czekam na poprawke

2023-11-27 07:39 UTC, majaomelaniuk commented
zmieniłam

2023-11-27 07:44 UTC, closed without merging

2023-11-27 07:47 UTC, mlodyhubson reviewed
dodaj lemura